Fixed 3.2c and 9.9
shd/logic2022 pull request #7
Opened 2022-05-27 16:41 UTC by FeorgeGeorge

Исправления к задачам 3.2с и 9.9 в ДЗ

2022-05-28 23:41 UTC, DK318 requested changes
Не очень понял, чем вам не понравилась формулировка задания 9.9

2022-05-28 23:41 UTC, DK318 commented on hw-theory.tex
> +Покажите, что либо между $a$ и $b$ есть биекция, сохраняющая порядок (такая, что $x < y$ влечёт $f(x) < f(y)$), либо есть иньективное отображение из одного множества в начальный отрезок другого, такж
```suggestion
Покажите, что либо между $a$ и $b$ есть биекция, сохраняющая порядок (такая, что $x < y$ влечёт $f(x) < f(y)$), либо есть инъективное отображение из одного множества в начальный отрезок другого, также сохранающее порядок.
```

2022-05-28 23:41 UTC, DK318 commented on hw-theory.tex
> +Покажите, что либо между $a$ и $b$ есть биекция, сохраняющая порядок (такая, что $x < y$ влечёт $f(x) < f(y)$), либо есть иньективное отображение из одного множества в начальный отрезок другого, такж
Если уж и делаете исправления, то, пожалуйста, не допускайте опечатки :smiley_cat:

2022-05-29 09:35 UTC, FeorgeGeorge commented on hw-theory.tex
> +Покажите, что либо между $a$ и $b$ есть биекция, сохраняющая порядок (такая, что $x < y$ влечёт $f(x) < f(y)$), либо есть иньективное отображение из одного множества в начальный отрезок другого, такж
Исходная постановка задачи неправильная потому что есть контрпример: функция из N в N f(x) = x' сохраняет порядок, но не переводит N в начальный отрезок и не является биекцией (стоило сразу так написать, извиняюсь).

2022-06-12 16:28 UTC, merged