Link updated
shd/logic2022 pull request #9
Opened 2022-06-08 22:39 UTC by Krisstopher

Засунул книжку в репозиторий, чтоб больше не терялась

2022-06-09 12:45 UTC, DK318 requested changes

2022-06-09 12:45 UTC, DK318 commented on README.md
> ++ В.Е.Плиско, В.Х.Хаханян, Интуиционистская логика, Мех-Мат МГУ 2009 (https://github.com/shd/logic2022/blob/master/intlog.pdf)
Если вы закидываете пдфку в репо, то почему бы не сделать относительную ссылку?

2022-06-09 15:39 UTC, Krisstopher commented on README.md
> ++ В.Е.Плиско, В.Х.Хаханян, Интуиционистская логика, Мех-Мат МГУ 2009 (https://github.com/shd/logic2022/blob/master/intlog.pdf)
Хм, а какова судьба репозитория?
Просто вижу, что конспекты прошлых лет лежат, соответственно, в репозиториях прошлых лет и не копируются в текущий.
Не забудут ли при создании logic2023 перенести этот файл?
С этой стороны мне кажется чуть более логичным оставить файл в репозитории logic2022 с соответствующей абсолютной ссылкой на него в README.

2022-06-09 21:02 UTC, DK318 commented on README.md
> ++ В.Е.Плиско, В.Х.Хаханян, Интуиционистская логика, Мех-Мат МГУ 2009 (https://github.com/shd/logic2022/blob/master/intlog.pdf)
:thinking:. Возможно стоит просто сделать обычную md ссылку и задать имя (по аналогии с ссылками на конспекты)

2022-06-10 14:14 UTC, Krisstopher commented on README.md
> ++ В.Е.Плиско, В.Х.Хаханян, Интуиционистская логика, Мех-Мат МГУ 2009 (https://github.com/shd/logic2022/blob/master/intlog.pdf)
Сделал
Могу ещё остальные ссылки к этому же формату привести и сделать кликабельные ссылки на слайды (относительные или абсолютные?) и конспекты, чтобы не приходилось скроллить вверх или открывать вторую вкладку.

2022-06-11 14:04 UTC, DK318 commented on README.md
> ++ В.Е.Плиско, В.Х.Хаханян, Интуиционистская логика, Мех-Мат МГУ 2009 (https://github.com/shd/logic2022/blob/master/intlog.pdf)
На слайды думаю не стоит, на конспекты вроде же есть ссылки

2022-06-11 19:39 UTC, Krisstopher commented on README.md
> ++ В.Е.Плиско, В.Х.Хаханян, Интуиционистская логика, Мех-Мат МГУ 2009 (https://github.com/shd/logic2022/blob/master/intlog.pdf)
Тогда всё готово

2022-06-12 16:34 UTC, shd commented
Чем мне не нравится идея с копированием книги в Гитхаб: книга-то не моя. Тогда надо разрешение их спрашивать по-хорошему, чтобы её у себя держать. Либо давайте это сделайте -- либо можно ограничиться названием (указанием новой ссылки).

2022-06-12 16:35 UTC, shd commented
Я бы ограничился ссылкой, т.к. книга ищется за 5 минут в гугле по названию.

2022-06-12 20:38 UTC, Krisstopher commented
Думаю, этот PR можно закрыть, т.к. ссылку исправил в предыдущем.

2022-06-13 21:14 UTC, closed without merging